=== apache/maven-build-cache-extension/src/main/resources/plugin-parameters/plugin-parameters.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
 Licensed to the Apache Software Foundation (ASF) under one or more
 contributor license agreements.  See the NOTICE file distributed with
 this work for additional information regarding copyright ownership.
 The ASF licenses this file to You under the Apache License, Version 2.0
 (the "License"); you may not use this file except in compliance with
 the License.  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://maven.apache.org/PLUGIN-PARAMETERS/1.0.0"
           xmlns="http://maven.apache.org/PLUGIN-PARAMETERS/1.0.0"
           elementFormDefault="qualified">

  <xs:element name="plugin" type="PluginType"/>
  <xs:element name="plugins" type="PluginsType"/>

  <xs:complexType name="PluginsType">
    <xs:sequence>
      <xs:element ref="plugin" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="PluginType">
    <xs:sequence>
      <xs:element name="groupId" type="xs:string"/>
      <xs:element name="artifactId" type="xs:string"/>
      <xs:element name="minVersion" type="xs:string" minOccurs="0"/>
      <xs:element name="goals" type="GoalsType"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="GoalsType">
    <xs:sequence>
      <xs:element name="goal" type="GoalType" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="GoalType">
    <xs:sequence>
      <xs:element name="name" type="xs:string"/>
      <xs:element name="parameters" type="ParametersType"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="ParametersType">
    <xs:sequence>
      <xs:element name="parameter" type="ParameterType" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="ParameterType">
    <xs:sequence>
      <xs:element name="name" type="xs:string"/>
      <xs:element name="type" type="ParameterTypeEnum"/>
      <xs:element name="description" type="xs:string" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

  <xs:simpleType name="ParameterTypeEnum">
    <xs:restriction base="xs:string">
      <xs:enumeration value="functional"/>
      <xs:enumeration value="behavioral"/>
    </xs:restriction>
  </xs:simpleType>

</xs:schema>

=== apache/maven-build-cache-extension/src/test/resources/plugin-parameters/maven-versioned-plugin.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
 Licensed to the Apache Software Foundation (ASF) under one or more
 contributor license agreements.  See the NOTICE file distributed with
 this work for additional information regarding copyright ownership.
 The ASF licenses this file to You under the Apache License, Version 2.0
 (the "License"); you may not use this file except in compliance with
 the License.  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
-->
<!--
  Test plugin demonstrating version-specific parameter definitions.
  This file shows how parameters change across plugin versions.
-->
<plugins xmlns="http://maven.apache.org/PLUGIN-PARAMETERS/1.0.0">
  <!-- Parameters for version 1.0.0-2.9.9 -->
  <plugin xmlns="http://maven.apache.org/PLUGIN-PARAMETERS/1.0.0"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://maven.apache.org/PLUGIN-PARAMETERS/1.0.0 plugin-parameters.xsd">
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-versioned-plugin</artifactId>
    <minVersion>1.0.0</minVersion>
    <goals>
      <goal>
        <name>execute</name>
        <parameters>
          <parameter>
            <name>legacyParameter</name>
            <type>functional</type>
            <description>Parameter available only in 1.x versions</description>
          </parameter>
          <parameter>
            <name>commonParameter</name>
            <type>functional</type>
            <description>Parameter available in all versions</description>
          </parameter>
        </parameters>
      </goal>
    </goals>
  </plugin>

  <!-- Parameters for version 3.0.0+ -->
  <plugin xmlns="http://maven.apache.org/PLUGIN-PARAMETERS/1.0.0">
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-versioned-plugin</artifactId>
    <minVersion>3.0.0</minVersion>
    <goals>
      <goal>
        <name>execute</name>
        <parameters>
          <parameter>
            <name>newParameter</name>
            <type>functional</type>
            <description>Parameter added in version 3.0.0</description>
          </parameter>
          <parameter>
            <name>commonParameter</name>
            <type>functional</type>
            <description>Parameter available in all versions</description>
          </parameter>
        </parameters>
      </goal>
    </goals>
  </plugin>
</plugins>

=== apache/maven-build-cache-extension/src/test/resources/plugin-parameters/maven-test-plugin.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
 Licensed to the Apache Software Foundation (ASF) under one or more
 contributor license agreements.  See the NOTICE file distributed with
 this work for additional information regarding copyright ownership.
 The ASF licenses this file to You under the Apache License, Version 2.0
 (the "License"); you may not use this file except in compliance with
 the License.  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
-->
<!-- Test plugin with version 1.0.0 parameters (deprecated 'oldParameter') -->
<plugin xmlns="http://maven.apache.org/PLUGIN-PARAMETERS/1.0.0"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://maven.apache.org/PLUGIN-PARAMETERS/1.0.0 plugin-parameters.xsd">
  <groupId>org.apache.maven.plugins</groupId>
  <artifactId>maven-test-plugin</artifactId>
  <goals>
    <goal>
      <name>test</name>
      <parameters>
        <parameter>
          <name>commonParameter</name>
          <cache-key>true</cache-key>
          <description>Parameter available in all versions; changing it changes the test result</description>
        </parameter>
        <parameter>
          <name>oldParameter</name>
          <cache-key>true</cache-key>
          <description>Parameter only in 1.x versions; changing it changes the test result</description>
        </parameter>
      </parameters>
    </goal>
  </goals>
</plugin>

=== apache/maven-build-cache-extension/src/main/resources/plugin-parameters/maven-install-plugin.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
 Licensed to the Apache Software Foundation (ASF) under one or more
 contributor license agreements.  See the NOTICE file distributed with
 this work for additional information regarding copyright ownership.
 The ASF licenses this file to You under the Apache License, Version 2.0
 (the "License"); you may not use this file except in compliance with
 the License.  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
-->
<plugin xmlns="http://maven.apache.org/PLUGIN-PARAMETERS/1.0.0"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://maven.apache.org/PLUGIN-PARAMETERS/1.0.0 plugin-parameters.xsd">
  <groupId>org.apache.maven.plugins</groupId>
  <artifactId>maven-install-plugin</artifactId>
  <minVersion>3.1.1</minVersion>

  <goals>
    <goal>
      <name>install</name>
      <parameters>
        <!-- FUNCTIONAL: Skipping installation changes the produced local repository -->
        <parameter>
          <name>skip</name>
          <type>functional</type>
          <description>Skip installation</description>
        </parameter>

        <!-- FUNCTIONAL: Affect installed artifacts or project state -->
        <parameter>
          <name>installAtEnd</name>
          <type>functional</type>
          <description>Install artifacts at end of multi-module build (changes installed project state on failure)</description>
        </parameter>
      </parameters>
    </goal>

    <goal>
      <name>install-file</name>
      <parameters>
        <!-- Same parameters as install goal -->
        <parameter>
          <name>file</name>
          <type>functional</type>
          <description>The file to install</description>
        </parameter>
        <parameter>
          <name>groupId</name>
          <type>functional</type>
          <description>GroupId of the artifact</description>
        </parameter>
        <parameter>
          <name>artifactId</name>
          <type>functional</type>
          <description>ArtifactId of the artifact</description>
        </parameter>
        <parameter>
          <name>version</name>
          <type>functional</type>
          <description>Version of the artifact</description>
        </parameter>
        <parameter>
          <name>packaging</name>
          <type>functional</type>
          <description>Packaging type of the artifact</description>
        </parameter>
        <parameter>
          <name>classifier</name>
          <type>functional</type>
          <description>Classifier of the artifact</description>
        </parameter>
        <parameter>
          <name>pomFile</name>
          <type>functional</type>
          <description>POM file to install</description>
        </parameter>
        <parameter>
          <name>generatePom</name>
          <type>functional</type>
          <description>Generate a minimal POM</description>
        </parameter>
        <parameter>
          <name>javadoc</name>
          <type>functional</type>
          <description>Javadoc artifact to install</description>
        </parameter>
        <parameter>
          <name>localRepositoryPath</name>
          <type>functional</type>
          <description>Local repository path</description>
        </parameter>
        <parameter>
          <name>sources</name>
          <type>functional</type>
          <description>Sources artifact to install</description>
        </parameter>
      </parameters>
    </goal>
  </goals>
</plugin>
